

export const ADD_DATA = 'ADD_DATA'
export const DELETE_DATA = 'DELETE_DATA'

export const FETCH_DATA = 'FETCH'
export const FETCH_DATA_FUFILLED = 'FETCH_FUFILLED'
export const FETCH_DATA_ERROR = 'FETCH_ERROR'
export const CHANGE_PAGE = 'CHANGE_PAGE'


export const SIGNUP  = 'SIGNUP';
export const SIGNUP_FUFILLED  = 'SIGNUP_FUFILLED';
export const SIGNIN = 'SIGNIN'
export const SIGNIN_FUFILLED = 'SIGNIN_FUFILLED'
export const SIGNOUT = 'SIGNOUT'
export const SIGNIN_GOOGLE = 'SIGNIN_GOOGLE'

export const ENTER_ROOM = 'ENTER_ROOM'
export const   ENTER_ROOM_FUFILLED = 'ENTER_ROOM_FUFILLED'
export const   ENTER_ROOM_FAILED = 'ENTER_ROOM_FAILED'

export const FETCH_PROFILE = 'FETCH_PROFILE'
export const FETCH_PROFILE_FUIFLLED = 'FETCH_PROFILE_FUIFLLED'
export const PROFILE_UNSUBSCRIPTION = 'PROFILE_UNSUBSCRIPTION'
